# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.0.dev27+g0d656c9.d20230810'
__version_tuple__ = version_tuple = (0, 1, 0, 'dev27', 'g0d656c9.d20230810')
