build-package-on-request:
    name: Build package  ${{ github.ref_name }}
    uses: RobertoAldea/System-Tools/.github/workflows/build_python_package_fork_repo.yml@develop
    with:
      package-name: ${{ github.ref_name }}
      package-path: "code/${{ github.ref_name }}"
      source-path: "code/${{ github.ref_name }}/src"
      python-version: "3.10"

  publish-package:
    name: Publish package ${{ github.ref_name }} to PyPi
    needs: build-package-on-request
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name:  ${{ github.ref_name }}
          path: ${{ github.ref_name }}/dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ${{ github.ref_name }}/dist/
